### ISSUE TITLE
[Feature Request] Scene-Specific Settings

### ISSUE THREAD

**Issue by acaccavano** [trdischat/lessfog#11]
Would it be possible to have scene-specific settings instead of global ones? I like the module, particularly the new update to allow us to change the unexplored opacity for players, but would really like to change this for specific scenes. The use case here is a world map, which I want to give an indication to the players where they have been without obscuring it too much, as it is a map they possess in-game. To do this I can reduce the "Darkness - Unexplored", but I don't want to change this for all the encounter maps.

**Comment by trdischat** [comment]
The newest version of the module now automatically adjusts the darkness of the Unexplored areas to compensate for higher Darkness settings in a scene.  This should keep the darkness of the Unexplored areas relatively constant, regardless of whether you are looking at a daytime or nighttime scene.  Hopefully, this should eliminate any need for a scene-specific setting for the Unexplored darkness in most cases.  I know that this does not really address your specific use case.  But creating scene-specific settings in this module would be a major undertaking, and it may be quite some time before I have time to consider it.
