### ISSUE TITLE
Update for 0.8.x

### ISSUE THREAD

**Issue by EvldoaTV** [trdischat/lessfog#12]
Unfortunately since the 0.8.6 less fog causes the fog of war and vision to no longer function, Love this Module hope to see an update in the near future

**Comment by trdischat** [comment]
The module is working fine on 0.8.6 on my system and I have no other reports of issues with 0.8.6.  Can you provide more information about what you are doing?  Have you tried disabling all other modules?

**Comment by trdischat** [comment]
New version of the module released.  Please confirm whether your issues have been addressed.

**Comment by EvldoaTV** [comment]
Well, I feel foolish.....I discovered the issue and appears it was operator error......apologies for possibly wasting your time appreciate the update either way love the module thanks again

**Comment by EvldoaTV** [comment]
Thanks again
