### ISSUE TITLE
Greyed Out GM Tools

### ISSUE THREAD

**Issue by Thanaban1** [trdischat/lessfog#13]
When the module is active, I cannot access the tools when logged in as a Gamemaster or Assistant Gamemaster.
They appear as grayed out and are non-responsive.
No problems when I'm logged in as a Player or Trusted Player.

Everything's fine when I activate all my other modules without The Furnace (which deactivate all its dependencies, including Lessfog).
Everything works fine if I activate all The Furnace dependencies by themselves (advanced-macros, initiative-double-click, dfreds-droppables and split-journal) without activating The Furnance and Lessfog.

Running Foundry 0.8.6 on DnD5e 1.3.3

**Comment by trdischat** [comment]
What tools are you talking about?  If you download and install all the modules that are listed as dependencies in the current version of The Furnace, you should be able to uninstall The Furnace completely.  As far as I know, it no longer has any code of its own and doesn't do anything.

**Comment by Thanaban1** [comment]
Don't know why, but it looks like I was missing an update or it didn't update completely when I switched to 0.8.6 and updated all my modules. Everything's fine now. 

Thank you for you quick reply, sorry for the trouble.
