### ISSUE TITLE
Use `canvas.perception.schedule({sight: {refresh: true}})`

### ISSUE THREAD

**Issue by dev7355608** [trdischat/lessfog#16]
Just a small thing I noticed. FVTT 0.8.2+ provides a new method of requesting refreshes. Instead of `canvas.sight.refresh()` it's probably best to use `canvas.perception.schedule({sight: {refresh: true}})`.

**Comment by trdischat** [comment]
Thanks for the suggestion. I will test it out and include this change in the next release.
