### ISSUE TITLE
Pith Black on unexplored areas not working.

### ISSUE THREAD

**Issue by Gorvaine** [trdischat/lessfog#17]
The alpha changes if you select and deselect the tokens.

**Comment by trdischat** [comment]
My apologies, but I don't understand this comment.

**Comment by Gorvaine** [comment]
I mean, Fog of war layer is always transparent for the GM.

**Comment by trdischat** [comment]
That’s the whole point of the module. If you want the unexplored areas to be hidden from the GM, then don’t use this module.

**Comment by Gorvaine** [comment]
Oh.. I thought that this button was malfunctioning because the background was always visible no matter if pressed or not.
https://i.imgur.com/PtZnWaq.jpeg

if that's intended no problem, oc.
https://streamable.com/yzm8dm

**Comment by trdischat** [comment]
Try setting the value for unexplored to 1.0 and see if that meets your needs.
