### ISSUE TITLE
GM doesnt get exploration update from unselected tokens

### ISSUE THREAD

**Issue by DieterKosken** [trdischat/lessfog#18]
As a player moves around, they explore. Unless the GM has the token selected while its moving, the exploration area does not update for the GM. So if the PC moves around while not selected by the GM, there is no historical view for the GM to see what the PC has explored. 

GM view
![gm-view](https://user-images.githubusercontent.com/41964137/130537877-45c73342-2ff3-4c04-939f-786809cc5c3c.PNG)

PC view - stepped in and out of hut
![pc-view](https://user-images.githubusercontent.com/41964137/130537881-0c7477e9-cc06-407c-9003-b7a602c3c0a5.PNG)

**Comment by trdischat** [comment]
This behavior is just how Foundry works.  This module does not cause this to happen. Try disabling this module and see for yourself.
