### ISSUE TITLE
Is it possible to make the out of line of sight areas of explored areas not be grey at all?   

### ISSUE THREAD

**Issue by Cull3411** [trdischat/lessfog#24]
Is it possible to make the out of line of sight areas of explored areas not be grey at all?   

Make it so that the color that indicates an area that is out of line of sight be the transparent color.

Going a step further with the idea.   Make it so that the effect depends on the type of wall blocking the LOS.   
2 terrain walls would cause the grey LOS shadow, but 1 regular wall would cause transparent LOS shadow.

**Comment by trdischat** [comment]
I think that what you are suggesting is more along the lines of what the [Perfect Vision module](https://github.com/dev7355608/perfect-vision) does. The goals of Less Fog are much less ambitious.  Please check out Perfect Vision and see if that is a step in the right direction.
