### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by Bryn1701** [trdischat/lessfog#3]
First of all, thanks for an amazing module. I love having control of how dark the fog is, it makes the game so much more subtle. 

But there is an issue. As the title says, I am having a compatibility issue with Less Fog since the recent update. When Combat Utility Belt, FXMaster and Token Attacher is enabled, there is this odd placement of anything FX, such as clouds, snow and rain etc when refreshed. If you enable the FX while all 3 are enabled, it works fine. It starts to "tear" when the programme/browser is refreshed.  I have tested this on both the stand alone Foundry and on The Forge. Same results. When one of these programmes is disabled, it works fine. But only Less Fog has updated recently, so it looks to be an issue with Less Fog itself playing nice with the other mentioned Modules. [Here](https://www.youtube.com/watch?v=WHx72_4V8fc&feature=youtu.be) is a link to a video showing the issue.

**Comment by trdischat** [comment]
Less fog was updated to deal with the complete rewrite of the lighting system in FVTT.  I don't use these other modules, and have no idea whether they have been updated to deal with the latest beta release of FVTT.  There really is nothing about less fog that should influence the placement of effects on the canvas.  But I will keep it in mind as we get closer to the stable release of version 0.7.5.

**Comment by trdischat** [comment]
I think I fixed the problem.  Please update to version 0.6.6 and let me know if it works for you.  Thanks.

**Comment by Bryn1701** [comment]
That does seem to have fixed things, thank you very much! I look forward to using Less fog in my game! Amazing!
