### ISSUE TITLE
Less Fog and Wall Height/Levels 

### ISSUE THREAD

**Issue by cgplayer2000** [trdischat/lessfog#30]
I had a problem where I could see doors from one level through to other levels.  Made this really tricky for tokens moving through the scene.  After coordinating with the author of Levels and Wall Height, and using FTC, it appears that Less Fog still doesn't work correctly with Levels/Wall Height.  

https://user-images.githubusercontent.com/10798879/221424130-71a3e2f0-6ad6-48dc-9de5-57490098ae96.mp4

I do have Fog Exploration ticked
![image](https://user-images.githubusercontent.com/10798879/221424227-4914e80c-e7da-4db8-983b-e98c8eadc95d.png)

**Comment by trdischat** [comment]
Less Fog automatically disables its "Reveal Tokens" feature if the Levels module is enabled.  So it should not interfere with Levels in any way.
