### ISSUE TITLE
Apply transparency to players

### ISSUE THREAD

**Issue by theruleslawyer** [trdischat/lessfog#31]
I'm trying to apply a more transparent fog for a digital table top, but the GM and player view look really different. Only the GM view gets the transparent fog. Can we have an option to apply to player view as well?

**Comment by trdischat** [comment]
There is already on option in the module to "Reveal to All Players" that does what you want.

**Comment by theruleslawyer** [comment]
That completely exposes all tokens out of LOS and means out of sight enemies can't move hidden.  What I was hoping for was Fog Opacity to apply to the the player view as well as the GM view. The fog is too dark on my DTT and I want to lighten it for players to see, not give them unlimited vision. Reveal to all players doesn't address the darkness issue at all.

**Comment by trdischat** [comment]
Try disabling "Reveal Tokens" and enabling "Reveal to All Players".  I know that this will hide the tokens from the GM as well, but at least the fog opacity will apply consistently to both the GM and the Players.  The GM can then use the "Toggle GM Vision" button to reveal everything on the map without showing it to the Players.
