### ISSUE TITLE
when selecting player view other tokens disappear in v11

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [trdischat/lessfog#32]
hi im having an issue as a gm. when you use this mod and select player vision, and scroll your mouse over tokens the tokens disappear. as seen in this gif.
![pf2 missing tokens](https://github.com/trdischat/lessfog/assets/62528192/39b1a15b-dce4-4804-a431-4398199b63e6)

**Comment by steveculshaw** [comment]
I'm seeing similar with tokens appearing/disappearing.
Checked my console, and no errors/warnings showing.

**Comment by trdischat** [comment]
Problem should be fixed in release 0.11.1.
