### ISSUE TITLE
Compatibility with PF2e's GM Vision function

### ISSUE THREAD

**Issue by DariusWolfe** [trdischat/lessfog#33]
Just discovered an issue that was really frustrating. 

PF2e adds a GM Vision function, with a button under lighting and a hotkey (Ctrl-G by default) that I did not realize was separate from the GM Vision function added by Less Fog. Apparently, you can have GM Vision turned on with both PF2e and Less Fog, in which case, toggling either one off does nothing; both must be toggled off for the normal vision mode to be restored.

I'm requesting that this incompatibility be investigated and resolved, as I'd rather not have to deal with this again, and I feel like it could easily become a pitfall for other users, especially considering how long it took me to figure out the issue.

**Comment by trdischat** [comment]
Fixed in release for FVTT version 12. Module button disabled when used with PF2e system.
