### ISSUE TITLE
0.7.3 Different Options Now, Lack of Opacity

### ISSUE THREAD

**Issue by fuzzlewump** [trdischat/lessfog#4]
![image](https://user-images.githubusercontent.com/72497607/95321499-ba468b00-0860-11eb-8c18-1b3a19e2ce4f.png)

These are the options I have for Less Fog now, looks completely different now, and I'm not sure they actually do anything. Not seeing options to set opacity anywhere.

Thanks for the great module!

This is on Foundry 0.7.3.

**Comment by trdischat** [comment]
The lighting system has completely changed in FVTT 0.7.X.  The old "opacity" settings do not even exist in the software anymore.  If you use higher numbers in the colors above, those areas will become lighter in the scene.  If you want them to remain uncolored and neutral, just make sure to use the same values for Red, Green, and Blue.  The colors above read as 0xRRGGBB.  So 0x7f7f7f is a 50% grey color, which is roughly the same as setting the opacity to 0.5.
