### ISSUE TITLE
[FEATURE Request] Player facing less fog

### ISSUE THREAD

**Issue by Flintwyrm** [trdischat/lessfog#5]
Would it be possible to have the same option of being able to see all other actors through fog like the GMs can ,but for players. 

This is good for simulating line of sight in a battle field but still be able to see the whole thing. This is specially good for games like LANCER.

**Comment by Grygon** [comment]
Bumping here as well--@trdischat any issues with my PR?

**Comment by ScyllPoesis** [comment]
More bumpage for support. Keep accidentally updating the module in Foundry and overwriting the fork that fixes this, would love to see it merged in.
